name = "telegram-openrouter-bot"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
DEFAULT_MODEL = "deepseek/deepseek-v4.1-flash"
IMAGE_MODEL = "google/gemma-4-26b-a4b-it:free"

[triggers]
crons = ["0 3 * * *"]

[[kv_namespaces]]
binding = "BOT_KV"
id = "7b5c53c1a2d448a582f9d51fb02a7f42"

[observability.logs]
enabled = false
invocation_logs = true